version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: votingapp
      MYSQL_DATABASE: votingapp
      MYSQL_USER: votingapp
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
  web:
    image: votingapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/votingapp
      SPRING_DATASOURCE_USERNAME: votingapp
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
