version: '3'
services:
  # Spring Boot application container
  spring-app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    ports:
      - "9002:9002"  # Map container port to host port
  # MySQL database container
  mysqldb:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: votingapp
      MYSQL_DATABASE: votingapp
      MYSQL_USER: votingapp
      MYSQL_PASSWORD: votingapp
    ports:
      - "3307:3306"  # Map container port to host port
